# Generated by Django 4.2.2 on 2023-07-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_ad_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
