# Generated by Django 4.2.2 on 2023-07-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(null=True, upload_to="logos/"),
        ),
    ]
